baseURL = "https://thefake.vip"
languageCode = "en-gb"
title = "TheFake VIP"

[params]
description = """
A visually impaired guy who's big into tech, Linux, and accessibility.
"""

[params.author]
name = "Michael Connor Buchan"
email = "mikey@blindcomputing.org"
url = "https://thefake.vip"

[markup]
  [markup.highlight]
    guessSyntax = true
    lineNos = true
    noClasses = false

[menu]
  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon (@thefake_vip@linuxrocks.online)"
  weight =  -80
  url = "https://linuxrocks.online/@thefake_vip"
  [[menu.social]]
  identifier = "twitter"
  name = "Twitter (@blind_comp)"
  weight = -70
  url = "https://twitter.com/blind_comp"
  [[menu.social]]
  identifier = "youtube"
  name = "YouTube (TheFake VIP)"
  weight = -60
  url = "https://www.youtube.com/channel/UCRUCCRK2TY0Ns0MlX0qVhYg"
  [[menu.social]]
  identifier = "github"
  name = "Github (mcb2003)"
  weight = -50
  url = "https://github.com/mcb2003"
  [[menu.social]]
  identifier = "gitlab"
  name = "Gitlab (mcb2003)"
  weight = -40
  url = "https://gitlab.com/mcb2003"
  [[menu.social]]
  identifier = "discord"
  name = "Discord (VIP Central server)"
  weight = -30
  url = "https://discord.gg/nzccydS"
  [[menu.social]]
  identifier = "keybase"
  name = "Keybase (thefake_vip)"
  weight = -20
  url = "https://keybase.io/thefake_vip"
  [[menu.social]]
  identifier = "facebook"
  name = "Facebook (Michael Buchan)"
  weight = -10
  url = "https://www.facebook.com/TheFakeVIP"

[module]
    [[module.imports]]
    path = "github.com/lower-elements/elemental"
    disable=false
