baseURL = "https://thefake.vip"
languageCode = "en-gb"
title = "TheFake VIP"
copyright = "Copyright © Michael Connor Buchan"

[params]
description = """
"""

[params.author]
name = "Michael Connor Buchan"
email = "mikey@blindcomputing.org"
url = "https://thefake.vip"

[params.elemental]
container = "container-md"

[menu]
  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon (@thefake_vip@linuxrocks.online)"
  weight =  -80
  url = "https://linuxrocks.online/@thefake_vip"
  [[menu.social]]
  identifier = "youtube"
  name = "YouTube (TheFake VIP)"
  weight = -60
  url = "https://www.youtube.com/channel/UCRUCCRK2TY0Ns0MlX0qVhYg"
  [[menu.social]]
  identifier = "discord"
  name = "Discord (@TheFakeVIP)"
  weight = -50
  url = "https://discord.com/users/295179787268259851"
  [[menu.social]]
  identifier = "github"
  name = "Github (mcb2003)"
  weight = -40
  url = "https://github.com/mcb2003"

[module]
    [[module.imports]]
    path = "github.com/lower-elements/elemental"
    disable=false
