baseURL = "https://thefake.vip"
languageCode = "en-gb"
title = "TheFake VIP"
copyright = "Copyright © Michael Connor Buchan"

[params]
shortTitle = "michael Buchan"
description = """\
    I write low-level software, resurrect obsolete hardware, build questionable networks, care deeply about free / open source software, and \
    believe computers and the software they run should be understandable, hackable and owned by the people using them.\
"""

[params.author]
name = "Michael Connor Buchan"
email = "mikey@blindcomputing.org"
url = "https://thefake.vip"

[params.elemental]
container = "container-md"

[menu]
  [[menu.social]]
  identifier = "envelope-fill"
  name = "Email (mikey@blindcomputing.org)"
  weight = -100
  url = "mailto:mikey@blindcomputing.org"
  params.rel = "noopener me"
  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon (@thefake_vip@linuxrocks.online)"
  weight =  -80
  url = "https://linuxrocks.online/@thefake_vip"
  params.rel = "noopener me"
  [[menu.social]]
  identifier = "youtube"
  name = "YouTube (TheFake VIP)"
  weight = -60
  url = "https://www.youtube.com/channel/UCRUCCRK2TY0Ns0MlX0qVhYg"
  params.rel = "noopener me"
  [[menu.social]]
  identifier = "discord"
  name = "Discord (@TheFakeVIP)"
  weight = -50
  url = "https://discord.com/users/295179787268259851"
  params.rel = "noopener me"
  [[menu.social]]
  identifier = "github"
  name = "Github (mcb2003)"
  weight = -40
  url = "https://github.com/mcb2003"
  params.rel = "noopener me"

[module]
    [[module.imports]]
    path = "github.com/lower-elements/elemental"
    disable=false
